language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install sphinx
script:
- make docs
deploy:
  provider: pypi
  user: renwei2
  password:
    secure: CrDmLCeZXNuNAnb4MsiH3ABr2oty9Rq88MMLBqbpUO/2N0n3V+jsi3lD9cMKIXkrk80uK2wipbbzS/3OBGskLxk+t+V0pd6x6WZ6SDt9AIZiLObAP/bSAknI0YKc2I9GcwpA7ubmzSMdtC9A3iFb9uer2LVjFOO880RuR6g/1Jjm3dreDGQOQqlcPZSX3JiTdybR/Xa+TR0fOMXQTAedEKR8kPdlSEp/Pva5qmk2DaJE2CvTtQZdsMuMe5k8CI0wpzOIfT4IAFTnjXNu8hns8y9vUT2Ck271AWPAloz59xJwsRQL8bMyF7Q+Gd0NqQXiXawM3rkGk1ZKsOYjYv6t7BuFRYP5pMHP30F+bj6k5cSz7GzLOZIfERnD28MPcE1XpMRBmUxQeeAg7G8TCv/oGkEhrRBF/JyXUw9WqpnAV513J6PTZr8cOhZshT9WWoLbSC6tNVt0cNRsD0vd3bx6WV9U02XNMyJ/vXfroOaYmnATGMbhxuFeWIzGn/JIMGOICqaf5t8bAtUMpPjmAOep05h8ClBQ7j3tCqc/n9xtAFBPXrOsKhuF5CI5DhPDvupM/cPEIbuoEMveRjfvLbFbklqyACMJPYBmebbbL4xHnIUIGZCMxK1otelwO5qHuHWNDLzMQaLD540zhzwGg+waDsaN1NJl3uYqol0WpKYRXts=
  on:
    tags: true
  distributions: sdist bdist_wheel
