language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install sphinx
script:
- make docs
deploy:
  provider: pypi
  user: renwei2
  password:
    secure: pJWedKIC5hZiJEvV6H9FWvccBx6Hpdt0fb22Ql5XbyCp9fJc7OUT902lgS2ogsxPaD0O+ovXW17ZylDfJFhEInFsJqTVBBU340LqywmPn1FxATMKSd2oaf9EWC5kk72XEYQ2pqVfE61A53vm653M+rxrZb9vvbaE31KR7g9MWsLBJOTEkkwxn3F7wJ3fLQEWtZKWxsy5ydwmACj0+uzCJLZJbrCmlwzVRXWY2430VlbMrIKMmgXKx3Dsy7Qzh7MQkd9qadG7ByYlwF4L+9blGSilRBq6A0t/jZTkC2cZdm93O9CLZqhI9QHkkOl1B2DgK3SIFAeH/GVxoQv4LZ6vY2ueRTkpmWL7mIwuUWVykJWnfnL9oKzZBogOCh9qWooDhC2BhSC58Imj7wcQrTWWUQuDKaihrS7RuQYV2wqGjbsOI7FJhbHhLy1QD717bHNUPVS2BXeYof1MvQRNjOgZjkWcry2RJO4RQVUk2qiq2nP/mm4UeDnL+zJPWxb5GllmnQQ9OdRLSA4nzEhZRomzlSSgKjHUEh2uQELvvto5xlnwugiyvud9VXuNIxX06DR7QNjm8UlvgWKOUowlNKJ/AGznsYeptBShONS2adQe/xKTadUctOLN0SbtBcfKWNiXa23ICY1rN/9nPX+DYBvi38J9KOVaBi74n3+Pq+ST3YM=
  on:
    tags: true
  distributions: sdist bdist_wheel
